### ISSUE TITLE
idea: add password strength checker

### ISSUE THREAD

**Issue by kamiloox** [xEdziu/KeepMyPassword-Desktop#12]
Users store passwords in your app. They are only managing them. But it could be a nice feature to have a password strength checker. If user inputs a password you might say to a user that the password is vulnerable. Somebody might have a really easy-to-break password and you could suggest changing it. 

It might be a challenging feature request but I believe users will appreciate this feature. Seriously, hardly anyone really knows about their password strength. 

I suggest using a regex to check if the password meets some criteria. Maybe even could exist a java library that could simplify the idea. Try to do your best. Users will really value this work.

**Comment by xEdziu** [comment]
## I am happy to inform that this feature will be added in next update!

### Here is a little preview:

Case 1: No password

![image](https://user-images.githubusercontent.com/50357817/158888689-ead3ef04-d3f1-4fe2-9cf8-299c921e1187.png)

Case 2: Weak password

![image](https://user-images.githubusercontent.com/50357817/158888761-47361d0a-282c-4a20-868a-087dc09d2666.png)

Case 3: Medium password

![image](https://user-images.githubusercontent.com/50357817/158888818-bebee78a-b14b-46de-9b46-6517d1c1ce84.png)

Case 4: Strong password

![image](https://user-images.githubusercontent.com/50357817/158889079-9fc4516a-1f08-426d-96b0-9ccdc24dcb4a.png)

I hope it is what you have expected!
