### ISSUE TITLE
bug: Language options change after trying to register with a weak password

### ISSUE THREAD

**Issue by alexia-nt** [xEdziu/KeepMyPassword-Desktop#156]
## **Actual behaviour**
After trying to register with a weak password, language options change and are shown as language tags.

## **Expected behaviour**
After trying to register with a weak password, the language options should not change.

## **Reproduce Steps**
1. Click register
2. Enter username and weak password
3. Choose language (optional)
4. Click register

## **Screenshots**
![error](https://user-images.githubusercontent.com/74093248/210178774-88a21d6f-26ca-457f-a4f4-bed2b5d38628.png)

## **Environment**
 - OS: Windows 11
 - App Version: 3.3.2
 
## **Exception Stack Trace**
There is not an error with stacktrace.

**Comment by xEdziu** [comment]
Hi, thanks for reporting this bug - I will work on that soon and repair that in the upcoming update

**Comment by xEdziu** [comment]
I think I managed to find the source of this bug - and I think i resolved it - Iit will be patched in next update
