### ISSUE TITLE
bug: Cannot register using a username that starts with 'err'

### ISSUE THREAD

**Issue by alexia-nt** [xEdziu/KeepMyPassword-Desktop#157]
## **Actual behaviour**
Cannot register using a username that starts with 'err' even though a strong password is entered.
The apps reloads the registration window and the 'err' is now removed from the username.

## **Expected behaviour**
Should be able to register using a username that starts with 'err'.

## **Reproduce Steps**
1. Click Register
2. Enter username that starts with 'err' and a strong password
3. Choose language (optional)
4. Click Register

## **Screenshots**
![snap1](https://user-images.githubusercontent.com/74093248/210269600-c12dba32-b5d2-47ba-95b7-e67c242abdf4.png)

![snap2](https://user-images.githubusercontent.com/74093248/210269612-31ecf02e-4044-46ee-b965-1815f83afe69.png)

## **Environment**
 - OS: Windows 11
 - App Version:  3.3.2
 
## **Exception Stack Trace**
There is not an error with stacktrace.

**Comment by xEdziu** [comment]
Hi, this is one of the app-design problems - but i think that now you will be able to register using name that starts with 'err'

**Comment by xEdziu** [comment]
I will include all changes in next update
