### ISSUE TITLE
bug: Generate Password error with 0 value

### ISSUE THREAD

**Issue by Nehomex** [xEdziu/KeepMyPassword-Desktop#16]
## **Expected behaviour**
Password with any length more than 0 should have let me create password with only one or few parameters

## **Actual behaviour**
When password has 0 in all inputs(expect lenght input)  it's work but if one of them contains value ~67% (eg. lenght = 6 any number = 4) password didn't create

## **Reproduce Steps**
1. Go to Generete password
2. Set any of inputs to any value (eg. lenght = 6 any number = 4)
3. Set generate 
4. See error (nothing happening)

## **Environment**
 - OS: Windows
 - App Version: 2.2.0

**Comment by xEdziu** [comment]
Noted. I will look at this problem tonight. You can expect a patch soon. 
Thanks a lot!

**Comment by xEdziu** [comment]
@all-contributors please add @Nehomex for test, bug and ideas
