### ISSUE TITLE
security enhancement: Password to app

### ISSUE THREAD

**Issue by Kubis10** [xEdziu/KeepMyPassword-Desktop#18]
## **Is your feature request related to a problem?**
An application that stores passwords should be secured so that you cannot enter a blank password

## **Describe the solution you'd like**
The application should verify that the password provided during registration is good enough

## **Describe alternatives you've considered**
There should be 2 password inputs: "password" and "repeat password" and there should be an option to see the entered password as plain text

**Comment by xEdziu** [comment]
Yea, that should be obvious. My bad. I will do that surely, thanks!
