### ISSUE TITLE
bug: Unexpected delay of wiping data

### ISSUE THREAD

**Issue by alozone** [xEdziu/KeepMyPassword-Desktop#19]
## **Expected behaviour**
Data should wipe out in the moment of action but it doesn't.

## **Environment**
 - OS: Linux
 - App Version: 2.2.1

![ezgif-5-bf9df11d66](https://user-images.githubusercontent.com/46488264/159373153-04c5a40b-c87c-4b43-9c83-5b77af3dcf01.gif)

**Comment by xEdziu** [comment]
Thanks for contributing!

**Comment by xEdziu** [comment]
@all-contributors please add @alozone for bug
