### ISSUE TITLE
translation: Looking for translators!

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/KeepMyPassword-Desktop#50]
## Help wanted!

Since ```v3.0.0``` I have added multi-language support for my application, so it is time to access wider audience.

For now (29.03.2022) only polish and english languages are supported. I wish that my app would be more accessible for people from another countries. 

So if you are interested in translating my app, here's a complete guide how to do it: [Translation Guide](https://github.com/xEdziu/KeepMyPassword-Desktop/wiki/Complete-Guide-for-Translators)

If you have any questions, feel free to start a discussion or comment this issue!

**Comment by b5i** [comment]
I'm currently working on the French translation

**Comment by xEdziu** [comment]
Wow! Thank you a lot! It means world to me ❤️

**Comment by jds1g14** [comment]
Hi, I'd like to work on the Portuguese translation (pt-PT) if that's ok ?

**Comment by neeoll** [comment]
Hey, do you mind if I get to work on one of the Spanish translations (es-PR)?

**Comment by xEdziu** [comment]
@neeoll sure, go on, thank you very much!

My work on this project is temporarily suspended due to my oncoming exams, but after them, I will continue my work!

**Comment by aestallon** [comment]
Hello there! More than happy to create a Hungarian translation!

**Comment by xEdziu** [comment]
@aestallon Great! <3
Feel free to make it! After your translation I will realease update with languages that has been added ( I finally have some time to do it). Thank you for your support!

**Comment by sierra41** [comment]
Hello,  I'd like to work to work on one of the Korean translation!

**Comment by xEdziu** [comment]
Hi @sierra41, feel free to work on it! I appreciate it!

**Comment by realZachi** [comment]
Hey! Im a student developer and looking to start contributing to OSP. I love your project and would love to start with it. If you don't mind, I'd like to start working on a German translation!

**Comment by xEdziu** [comment]
> Hey! Im a student developer and looking to start contributing to OSP. I love your project and would love to start with it. If you don't mind, I'd like to start working on a German translation! 

That would be great! ❤️

**Comment by realZachi** [comment]
> 

However this is going to go, please keep your positive and thankful attitude, I love it!

**Comment by xEdziu** [comment]
> > 
> 
> However this is going to go, please keep your positive and thankful attitude, I love it!

Comments like this make me really want to come back to updating this project in my little free time, thank all of you, that support this open source and free idea ❤️

**Comment by xEdziu** [comment]
@Nacho321 Thanks a lot man! I really appreciate the effort. I'm happy to let others grow with me!

**Comment by ayushdotdev** [comment]
Hi @xEdziu, I am student developer. I can do Hindi Translation

**Comment by shavy4452** [comment]
Hi @xEdziu , I am a full stack developer from India. I am interested in working with you on this translation issue. I can do the hindi translation.

**Comment by stefanoleggio** [comment]
Hi @xEdziu, I can do the Italian traslation

**Comment by RowinRuizendaal** [comment]
If needed I can help with the Dutch translation

**Comment by hitblast** [comment]
Hi @xEdziu ! Glad to hear about your project from Hacktoberfest's Discord server. I'd like to contribute to the Bengali translation of the app.

**Comment by xEdziu** [comment]
Hi @ayushdotdev and @shavy4452, Hindi translation already exists, so you can check if the spelling is correct.
Here is a link to the Hindi translation: https://github.com/xEdziu/KeepMyPassword-Desktop/blob/main/src/main/resources/language_hi-in.properties

**Comment by xEdziu** [comment]
Hello @stefanoleggio, @RowinRuizendaal and @hitblast - I am more than happy that you are willing to help improve my project. Feel free to translate it into your languages, thank you a lot in advance!

**Comment by wildanfadh** [comment]
Hi @xEdziu I will help to do the Indonesian translation

**Comment by xEdziu** [comment]
Hi @wildanfadh, feel free to do it, thank you a lot!

**Comment by Kit-p** [comment]
Hi @xEdziu, I'm a dev from Hong Kong, will have a take on traditional Chinese (zh-hk)

**Comment by varunnitian** [comment]
I would like to do this @xEdziu can you assign it to me? I'd like to contribute to the Gujarati Translation of the app.

**Comment by xEdziu** [comment]
Hello @Kit-p! Thank you! Can't wait for the traditional Chinese translation!

**Comment by xEdziu** [comment]
Hello @varunnitian, I will not assign this issue to anyone, since it has too many contributors, but I am still waiting for translation PR from you! <3

**Comment by justDabuK** [comment]
Just saw you post on the Hacktoberfest Discrod server, I'd be happy to add a german translation 👌🏽

**Comment by xEdziu** [comment]
Hi @justDabuK, please acknowledge yourself with this discussion: [Hacktoberfest Contribution](https://github.com/xEdziu/KeepMyPassword-Desktop/discussions/88), thank you for your will to contribute to open-source! <3

**Comment by Bedovan** [comment]
Hi! i would be more than happy to add the Turkish translation - started working on it already!

**Comment by xEdziu** [comment]
Hello @Bedovan, that is fantastic! Thank you very much!

**Comment by maharshi-sinha** [comment]
Hi, @xEdziu I found some mistakes in the Hindi section, and would love to fix them all.

**Comment by xEdziu** [comment]
Hi @maharshi-sinha, thank you! Feel free to improve this section!

**Comment by Korak-Sengupta** [comment]
Hello @xEdziu , would like to make a Bengali language version for this, if you allow.

**Comment by xEdziu** [comment]
Hello @Korak-Sengupta, feel free to make a Bengali version for this app, thank you a lot!

**Comment by hitblast** [comment]
> Hello xEdziu , would like to make a Bengali language version for this, if you allow.

@Korak-Sengupta I have already forked the repository to work on a Bengali version. Wanna work together on this?

**Comment by ehda93** [comment]
Hi! Is the german translation already finished? If not, i would like to work on this.

**Comment by xEdziu** [comment]
Hi @ehda93, I believe the german translation is already finished, but you can check if it is correct and improve it :D

**Comment by ehda93** [comment]
Hi, Thank you for your fast answer. I made some small improvements and created a PR.

**Comment by rudrakshkarpe** [comment]
Hi @xEdziu, I would like to add Marathi translations, please let me know your opinion

**Comment by vrabe** [comment]
Can I add traditional Chinese for Taiwan (zh-tw)? It's a little different to the one that Hong Kong use.

**Comment by arefathi** [comment]
Hello @xEdziu, I would like to work on the Amharic translation (my native language). I can also start on the Arabic sections but I am not that versed in technical phrases in Arabic - just conversational. Thanks.
I have always been fascinated with security tools such as your password management tool. Looks great!

**Comment by arefathi** [comment]
> Hello @xEdziu, I would like to work on the Amharic translation (my native language). I can also start on the Arabic sections but I am not that versed in technical phrases in Arabic - just conversational. Thanks. I have always been fascinated with security tools such as your password management tool. Looks great!

I am not sure Amharic language is supported by JRE8 - I don't see it on the list. Let me know if there is a workaround for that, and would be happy to contribute to that.

**Comment by xEdziu** [comment]
Hello @rudrakshkarpe, feel free to add your translation!

**Comment by xEdziu** [comment]
Hi @vrabe, I can't wait for your translation!

**Comment by xEdziu** [comment]
Hello @arefathi, I think that if you will use ```ar-ah``` locale, I will manage to make a workaround for it :D

**Comment by arefathi** [comment]
> Hello @arefathi, I think that if you will use `ar-am` locale, I will manage to make a workaround for it :D

Thanks for the reply. I am afraid that Amharic and Arabic are totally different languages, I just happen to speak both -  there are multiple Arabic variations on the site you shared but no Amharic support. I am not sure what to do about the Amharic. 

I can try to work on Arabic with one of the variations with Google Translate's assistance - as I am not fluent (just conversational). Let me know if there is a way you can handle the Amharic language.

**Comment by xEdziu** [comment]
> > Hello @arefathi, I think that if you will use `ar-am` locale, I will manage to make a workaround for it :D
> 
> Thanks for the reply. I am afraid that Amharic and Arabic are totally different languages, I just happen to speak both - there are multiple Arabic variations on the site you shared but no Amharic support. I am not sure what to do about the Amharic.
> 
> I can try to work on Arabic with one of the variations with Google Translate's assistance - as I am not fluent (just conversational). Let me know if there is a way you can handle the Amharic language.

So we will do it like that - since I am lazy please use ```single-am``` for my information that this is only Amharic translation. Is that okay with you?

**Comment by arefathi** [comment]
Yeah, sure. I can work on the Amharic -  you would figure out the locale problem. I started earlier and noticed that - so wanted your input. Thanks. I will try to send a PR later on.

started earlier 😄 ⬇️ 

add=ጨምር
adding.new.password=አዲስ የይለፍ ቃል ጨምር
appName=Keep My Password
cancel=ተው

**Comment by xEdziu** [comment]
@arefathi That is so cool! Thank you a lot!

**Comment by rudrakshkarpe** [comment]
> Hello @rudrakshkarpe, feel free to add your translation!

Thank you so much! I have raised a PR with the MA-EN Translations

**Comment by xEdziu** [comment]
> > Hello @rudrakshkarpe, feel free to add your translation!
> 
> Thank you so much! I have raised a PR with the MA-EN Translations

Hi, I don't see your PR

**Comment by rudrakshkarpe** [comment]
> > > Hello @rudrakshkarpe, feel free to add your translation!
> > 
> > 
> > Thank you so much! I have raised a PR with the MA-EN Translations
> 
> Hi, I don't see your PR

It's #98

**Comment by arefathi** [comment]
> @arefathi That is so cool! Thank you a lot!

@xEdziu I submitted that PR #100 
I hope it is to your standard, named it as you suggested `single-am` so that it stands out. 
Thanks!

**Comment by Saurabh-2809** [comment]
Hi @xEdziu, I have added a translation file to Nepali and also given two improvements in Hindi Translation, could you please look into it and let me know if you have any concerns regarding that?

**Comment by fmassaretto** [comment]
Hi @xEdziu I can help with pt-br (Brazilian Portuguese) translation. I know someone is already translating for pt-pt but there some words that are different. Is it ok?

**Comment by xEdziu** [comment]
@fmassaretto hi, there is no problem, I am waiting for your translation! ❤️

**Comment by fmassaretto** [comment]
> @fmassaretto hi, there is no problem, I am waiting for your translation! ❤️

it's done. Please, as it's my first PR here let me know if everything is good (or not :) ). Thanks!

**Comment by hasnain003** [comment]
@xEdziu I would like to work on the urdu translators for this.

**Comment by HawkItzme** [comment]
Hey @xEdziu and @anjannair  I would like to do few changes in  Hindi translation. Can I?

**Comment by xEdziu** [comment]
Hi @HawkItzme, there is no problem for me as long as all translations will be correct :D

**Comment by anjannair** [comment]
@HawkItzme go on!

**Comment by advaith017** [comment]
Hey @xEdziu! Can I add Kannada (South Indian language) to the list?

**Comment by xEdziu** [comment]
@advaith017 Sure, go on!

**Comment by minna-xD** [comment]
Hi @xEdziu ! I'd like to add Finnish.

**Comment by xEdziu** [comment]
Hello @minna-xD ,I am waiting for Finnish translation! ❤️

**Comment by minna-xD** [comment]
PR #131 created for Finnish

**Comment by mithindev** [comment]
Hi @xEdziu ! I'd like to add Tamil (தமிழ்), a South Indian Language.

**Comment by mithindev** [comment]
Hi @xEdziu ! I'd like to add malayalam (മലയാളം), a South Indian Language.

**Comment by mithindev** [comment]
Hi, @xEdziu I can also help with the Russian language. What locale should I use? Can I use `single-ru`

**Comment by xEdziu** [comment]
Hi @mithindev, for Malayalam please use ```single-ma-in``` and for Russian locale that you suggested would be ideal :) Thank you very much!

**Comment by mithindev** [comment]
Thank you so much i will make the PRs within 12:00 today ma'am.

**Comment by riteshnith27** [comment]
Hi @xEdziu i can do the tamil translation.

**Comment by MadhukeshSingh** [comment]
Hi @xEdziu  I would like to add Kannada translations

**Comment by mrjayrai** [comment]
Hi @xEdziu I would like to add Finnish Translation, can i help with it?

**Comment by hahayusuf** [comment]
Hello 

I am happy to provide an arabic translation for the app.

**Comment by xEdziu** [comment]
@hahayusuf hi, feel free to make translation!

**Comment by levo-7** [comment]
I would like to work on german translation

**Comment by xEdziu** [comment]
Hello @levo-7, there is an existing german translation file, but you can try to improve it if you wish :)

**Comment by alexia-nt** [comment]
Hello! I added the greek translation and created a pull request. Can you please merge it? :)

**Comment by projectnoa** [comment]
Is there any more Spanish translation needed?

**Comment by xEdziu** [comment]
@everyone!

THANK YOU ALL FOR YOUR SUPPORT!

IT WOULD BE POSSIBLE WITH YA ALL <3
