### ISSUE TITLE
idea: Change directory for config and database files

### ISSUE THREAD

**Issue by Nehomex** [xEdziu/KeepMyPassword-Desktop#6]
# **Is your feature request related to a problem? Please describe.**
No, it isn't

# **Describe the solution you'd like**
Instead of creating files in execute location, create directory in Local appdata(in windows) to avoid losing files or simple for convenience

# **Describe alternatives you've considered**
User could set files location manually (or both)

**Comment by xEdziu** [comment]
That's a great idea. I will try to make it asap ❤️

**Comment by xEdziu** [comment]
@Nehomex please check new beta release to see if this solution is suiting your needs and if needed, start a discussion here: #8
