### ISSUE TITLE
idea: Linux app launch icon shortcut

### ISSUE THREAD

**Issue by zaxonspox** [xEdziu/KeepMyPassword-Desktop#66]
Please add an .desktop file to launch application not from Terminal, like the below code:
**KeepMyPassword.desktop**
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=Keep My Password
Comment=Keep My Password
Exec=java -jar /opt/KeepMyPassword/KeepMyPassword-Desktop-3.0.0-linux.jar
Terminal=false
Icon=/opt/KeepMyPassword/access-32.png
```

Or even add an Linux install script, something like:
**INSTALL.sh**
```
#!/bin/bash
sudo mkdir -p /opt/KeepMyPassword
sudo cp $PWD/KeepMyPassword-Desktop-3.0.0-linux.jar /opt/KeepMyPassword/
sudo cp $PWD/access-32.png /opt/KeepMyPassword/
```
Partially tested - files in one dir: INSTALL.sh access-32.png KeepMyPassword-Desktop-3.0.0-linux.jar

**Comment by xEdziu** [comment]
@all-contributors please add @zaxonspox for design. example and ideas

**Comment by xEdziu** [comment]
@all-contributors please add @anjannair for code. example and translation
