### ISSUE TITLE
idea: hidden password support

### ISSUE THREAD

**Issue by kamiloox** [xEdziu/KeepMyPassword-Desktop#7]
By default, all passwords are visible directly to a user. This is correct behavior, but what if somebody is looking at us while we are watching our data?

I want to have my passwords hidden on startup unless I'd mark them as visible.

It will be best if it'd look like HTML input with type password - it's dotted (You can use asterisks - a matter of your preference).

![comparison](https://user-images.githubusercontent.com/45523480/158271185-3a1d195c-b443-411d-822e-0fc2c0ea14ef.jpg)

**Comment by xEdziu** [comment]
That's a great idea - it will be surely done in the future

**Comment by xEdziu** [comment]
@all-contributors please add @kamiloox for test, ideas and doc
